version: "3.9"

services:
  pgdata:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
  web:
    build: .
    command: python ./brandquad/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - pgdata

volumes:
  pgdata:
    external: true
